#define BAUD 9600
#define MSG_LENGTH 32



#define SENSOR_RC_PREFIX 0xd
#define SENSOR_RC_PREFIX_LEN 4
#define SENSOR_RC_PREFIX_POS (MSG_LENGTH - SENSOR_RC_PREFIX_LEN)


#define TEMP_LEN  8

#define TURB_LEN 10
#define TURB_POS (SENSOR_RC_PREFIX_POS - TURB_LEN)
#define TEMP1_POS  (TURB_POS - TEMP_LEN)
#define TEMP0_POS  (TEMP1_POS -TEMP_LEN)


#define CONTROL_RC_PREFIX 0xa
#define CONTROL_RC_PREFIX_LEN 4
#define CONTROL_RC_PREFIX_POS (MSG_LENGTH - CONTROL_RC_PREFIX_LEN)
#define CONTROL_S1_POS 0
#define CONTROL_S2_POS 1
#define CONTROL_S3_POS 2
#define CONTROL_J_POS 3




#define SENSOR_SEND_FRQ 200 //ms
#define SENSOR_REPEAT_TRANSMISSION 8 //ms





